on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - migrate-to-actions
jobs:
  test:
    env:
      GO111MODULE: on
    strategy:
      fail-fast: true
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@37335c7bb261b353407cff977110895fa0b4f7d8
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - name: Setup
      run: sudo apt-get -y install httpie
    - name: Run go vet
      run: make vet
    - name: Install vault, nomad, consul
      run: |
        ./scripts/getnomad.sh
        ./scripts/getvault.sh
        ./scripts/getconsul.sh
    - name: Start nomad
      env:
        NOMAD_LICENSE: ${{ secrets.NOMAD_LICENSE }}
      run: |
        ./scripts/start-nomad.sh
    - name: Run acceptance tests
      run: NOMAD_TOKEN=${{ env.NOMAD_TOKEN }} make testacc
    - name: Stop nomad
      run: ./scripts/stop-nomad.sh
