on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - migrate-to-actions
jobs:
  test:
    env:
      GO111MODULE: on
      VAULT_TEST_TOKEN: terraform-provider-nomad-token
      VAULT_ADDR: http://localhost:8200
    strategy:
      fail-fast: true
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@37335c7bb261b353407cff977110895fa0b4f7d8
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.RO_DOCKERHUB_USER }}
        password: ${{ secrets.RO_DOCKERHUB_TOKEN }}
    - name: Setup
      run: sudo apt-get -y install httpie
    - name: Install vault, nomad, consul
      run: |
        ./scripts/getnomad.sh
        ./scripts/getvault.sh
        ./scripts/getconsul.sh
    - name: Start nomad
      run: |
        # bash scripts/start-nomad.sh
        vault server -dev -dev-root-token-id=$VAULT_TEST_TOKEN > /dev/null 2>&1 &
        consul agent -dev > /dev/null 2>&1 &
        sudo nomad agent -dev -bind 0.0.0.0 -acl-enabled -vault-address=$VAULT_ADDR -vault-token $VAULT_TEST_TOKEN -vault-enabled -vault-allow-unauthenticated=false > /dev/null 2>&1 &
        export "TEST_NOMAD_TOKEN=$!" >> $GITHUB_ENV
        sleep 10
        nomad node status
        http --ignore-stdin POST http://localhost:4646/v1/acl/bootstrap | jq -r '.SecretID' > /tmp/nomad-test.token
        # echo "TEST_NOMAD_TOKEN=$(cat /tmp/nomad-test.token)" >> $GITHUB_ENV
    - name: Run go vet
      run: make vet
    - name: Run acceptance tests
      run: ${{ env.TEST_NOMAD_TOKEN }} make testacc
    - name: Stop nomad
      run: ./scripts/stop-nomad.sh
